#!/bin/bash
# Build hooks docs:
# https://docs.docker.com/docker-cloud/builds/advanced/#override-build-test-or-push-commands
echo "Now in `pwd`"
echo "Building small"
echo "Path: $DOCKERFILE_PATH"
echo "Image: $IMAGE_NAME"
build_scheme(){
    scheme_name="$1"
    scheme_suffix="$2"
    IMAGE_NAME="$DOCKER_REPO:tl-$scheme_name"
    if [ ! -z "$scheme_suffix" ]; then
      IMAGE_NAME="$IMAGE_NAME-$scheme_suffix"
    fi
    export IMAGE_NAME;
    echo "Building actual $scheme_name"
    docker build --build-arg scheme="$scheme_name" -t "$IMAGE_NAME" -f "$DOCKERFILE_PATH" .
    echo "Pushing $scheme_name ($IMAGE_NAME)"
    docker push $IMAGE_NAME
}
add_tag(){
  existing_tag="$1"
  new_tag="$2"
  docker tag "$DOCKER_REPO:$existing_tag" "$DOCKER_REPO:$new_tag"
  docker push "$DOCKER_REPO:$existing_tag"
}
set_latest(){
  target_suffix="$1"
  add_tag "tl-small-$target_suffix" "tl-small"
  add_tag "tl-small-$target_suffix" "tl-small:latest"
  add_tag "tl-medium-$target_suffix" "tl-medium"
  add_tag "tl-medium-$target_suffix" "tl-medium:latest"
  add_tag "tl-full-$target_suffix" "tl-full"
  add_tag "tl-full-$target_suffix" "tl-full:latest"
}
build_schemes(){
  build_scheme "small" "2018"
  # build_scheme "medium" "2018"
  # build_scheme "full" "2018"
  set_latest "2018"
}
build_schemes
