#!/bin/bash
# Build hooks docs:
# https://docs.docker.com/docker-cloud/builds/advanced/#override-build-test-or-push-commands
if [ -z $LOCAL_DOCKER ]; then
  echo "NOT BUILDING LOCAL DOCKER"
else
  echo "BUILDING DOCKER LOCALLY. ONLY BUILDING SMALL BY DEFAULT."
fi
echo "Now in `pwd`"
echo "Building small"
echo "Path: $DOCKERFILE_PATH"
echo "Image: $IMAGE_NAME"
echo ""


# repo_2018=""

build_scheme(){
  scheme_name="$1"
  tl_version="$2"
  tar_install_url="$3"
  ctan_repo="$4"
  IMAGE_NAME="$DOCKER_REPO:tl-$scheme_name"
  if [ ! -z "$tl_version" ]; then
    IMAGE_NAME="$IMAGE_NAME-$tl_version"
  fi
  export IMAGE_NAME;
  echo "Building actual $scheme_name ($IMAGE_NAME)"
  docker build \
    --build-arg scheme="$scheme_name" \
    --build-arg tl_version="$2" \
    --build-arg installfile="$tar_install_url" \
    --build-arg ctan_repo="$ctan_repo" \
    -t "$IMAGE_NAME" -f "$DOCKERFILE_PATH" .

  if [ -z "$LOCAL_DOCKER" ]; then
    echo "Pushing $scheme_name ($IMAGE_NAME)"
    docker push $IMAGE_NAME
  fi
}
add_tag(){
  existing_tag="$1"
  new_tag="$2"
  docker tag "$DOCKER_REPO:$existing_tag" "$DOCKER_REPO:$new_tag"
  if [ -z "$LOCAL_DOCKER" ]; then
    echo "Pushing updated $DOCKER_REPO:$existing_tag with new tag $DOCKER_REPO:$new_tag"
    docker push "$DOCKER_REPO:$existing_tag"
  fi
}
set_latest(){
  target_suffix="$1"
  add_tag "tl-small-$target_suffix" "tl-small"
  add_tag "tl-small-$target_suffix" "tl-small-latest"
  if [ -z "$LOCAL_DOCKER" ]; then
    add_tag "tl-medium-$target_suffix" "tl-medium"
    add_tag "tl-medium-$target_suffix" "tl-medium-latest"
    add_tag "tl-full-$target_suffix" "tl-full"
    add_tag "tl-full-$target_suffix" "tl-full-latest"
  fi
}
build_schemes(){
  tl_version="$1"
  tar_file="$2"
  repo="$3"
  if [ -z "$LOCAL_DOCKER" ]; then
    build_scheme "small" "$tl_version" "$tar_file" "$repo"
    build_scheme "medium" "$tl_version" "$tar_file" "$repo"
    build_scheme "full" "$tl_version" "$tar_file" "$repo"
  else
    build_scheme "minimal" "$tl_version" "$tar_file" "$repo"
  fi
}
# Remember to update repovars.env too
tar_2018="http://ftp.math.utah.edu/pub/tex/historic/systems/texlive/2018/tlnet-final/install-tl-unx.tar.gz"
repo_2018="http://ftp.math.utah.edu/pub/tex/historic/systems/texlive/2018/tlnet-final/"
tar_2019="http://ftp.math.utah.edu/pub/tex/historic/systems/texlive/2019/install-tl-unx.tar.gz"
repo_2019="https://ctan.crest.fr/tex-archive/systems/texlive/tlnet/"

build_schemes "2018" "$tar_2018" "$repo_2018"
# build_schemes "2019" "$tar_2019" "$repo_2019" "$repo_2019"
# set_latest "2019"
